[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bridge = "8EmkexKZB4XL4k2TkvEDyyWNKvrY7zxCw9SVQxF14GaJ"
message = "7HVZ6xxrdeVdWs5jDJoJBBxqv4gm4shM8SCtwxSsmgSb"

[registry]
url = "http://13.215.160.229:8899"

[provider]
cluster = "http://13.215.160.229:8899"
wallet = "~/.config/solana/id.json"

[scripts]
bridge = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/bridge.ts"
message = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/message.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
view = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/view.ts"